---
name: "Setup vvctl"
description: "Download and install vvctl CLI tool"
author: "Ververica"

inputs:
  version:
    description: "Version of vvctl to install (e.g. v1.2.3). If not specified, installs the latest stable release."
    required: false
    default: ""

  prerelease:
    description: "Install the latest prerelease version instead of stable release"
    required: false
    default: "false"

  install-dir:
    description: "Directory to install vvctl binary"
    required: false
    default: "/usr/local/bin"

outputs:
  version:
    description: "The version of vvctl that was installed"
    value: ${{ steps.install.outputs.version }}

  install-path:
    description: "The full path where vvctl was installed"
    value: ${{ steps.install.outputs.install-path }}

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [ "${{ inputs.prerelease }}" = "true" ] && [ -n "${{ inputs.version }}" ]; then
          echo "Error: Cannot specify both version and prerelease=true" >&2
          exit 1
        fi

    - name: Install vvctl
      id: install
      shell: bash
      env:
        INSTALL_DIR: ${{ inputs.install-dir }}
      run: |
        # Download the install script
        curl -fsSL https://raw.githubusercontent.com/ververica/vvctl/main/install.sh -o install.sh
        chmod +x install.sh

        # Determine arguments to pass to install script
        if [ "${{ inputs.prerelease }}" = "true" ]; then
          echo "Installing latest prerelease..."
          ./install.sh --preview
        elif [ -n "${{ inputs.version }}" ]; then
          echo "Installing version ${{ inputs.version }}..."
          ./install.sh "${{ inputs.version }}"
        else
          echo "Installing latest stable version..."
          ./install.sh
        fi

        # Set outputs
        INSTALLED_VERSION=$(${INSTALL_DIR}/vvctl --version | awk '/^[0-9]/{print $1; exit}')
        echo "version=${INSTALLED_VERSION}" >> $GITHUB_OUTPUT
        echo "install-path=${INSTALL_DIR}/vvctl" >> $GITHUB_OUTPUT

        # Add to PATH if not already there
        if [[ ":$PATH:" != *":${INSTALL_DIR}:"* ]]; then
          echo "${INSTALL_DIR}" >> $GITHUB_PATH
        fi

    - name: Verify installation
      shell: bash
      run: |
        if ! command -v vvctl &> /dev/null; then
          echo "Error: vvctl installation failed or not in PATH" >&2
          exit 1
        fi

        echo "✅ vvctl installed successfully!"

branding:
  icon: "download"
  color: "blue"
