name: Test vvctl Installation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-vvctl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup vvctl
      uses: ververica/vvctl@main
      
    - name: Print vvctl version
      run: vvctl --version